version: "3"

services:
    web:
        build:
            context: ./docker
        image: nygmarose/glamsquad:latest
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.15"
                    memory: 512M
                reservations:
                    cpus: "0.05"
                    memory: 28M
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 60s
        ports:
            - 80:80
            - 443:443
        networks:
            - webnet
        volumes:
            - ../:/var/www/html
            - ./docker/media:/srv/nr-glam-squad/media

    rabbit:
        image: rabbitmq:3
        hostname: rabbit
        deploy:
            resources:
                limits:
                    cpus: "0.15"
                    memory: 512M
                reservations:
                    cpus: "0.05"
                    memory: 28M
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 60s
        ports:
            - 5672:5672
        networks:
            - webnet

    tasker:
        build:
            context: ./docker/tasker
        image: bin_tasker:latest
        hostname: tasker
        deploy:
            resources:
                limits:
                    cpus: "0.15"
                    memory: 256M
                reservations:
                    cpus: "0.05"
                    memory: 28M
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 60s
        networks:
            - webnet
        volumes:
            - ../:/var/www/html

    redis:
        image: redis:latest
        hostname: redis
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.15"
                    memory: 768M
                reservations:
                    cpus: "0.05"
                    memory: 28M
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 60s
        networks:
            - webnet
        ports:
            - 6379:6379

networks: 
    webnet:
